# triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#
# triangle	 	tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# pentagonal	 	pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# hexagonal	 	hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# it can be verified that t285 = p165 = h143 = 40755.
#
# find the next triangle number that is also pentagonal and hexagonal.

t_set = {}
p_set = set()
h_set = set()

import itertools
for i in itertools.count():
    n = i + 1
    t = (n ** 2 + n) / 2

    t_set[i] = t
    p_set.add((3 * n ** 2 - n) / 2)
    h_set.add(2 * n ** 2 - n)

    if i > 285 and t in p_set and t in h_set:
        print(t)
        break


