# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


prev = 1
cur = 2
sum = cur
while cur < 4000000:
    tmp = prev + cur
    prev = cur
    cur = tmp
    if cur % 2 == 0:
        sum += cur
print(sum)
